[package]
name = "nih_plug_webview"
version = "0.0.0"
edition = "2021"
authors = ["Max Huttunen <max.huttunen@gmail.com>"]
license = "ISC"

description = "An adapter to use webview GUIs with NIH-plug"

[dependencies]
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git" }
serde_json = "1.0"
raw-window-handle = "0.4.3"
wry = { path = "../wry" }
parking_lot = "0.12.1"

[target.'cfg(target_os = "macos")'.dependencies]
cacao = { git = "https://github.com/maxjvh/cacao", branch = "trunk", features = ["webview", "appkit"] }
